Portfolio Mobile skeleton
telanet/My-Portfolio pull request #1
Opened 2022-03-15 17:11 UTC by telanet

### In this milestone I:

- Set up a new repository using best practices
- Parse a Figma design to create a UI
- Build the first two sections of the mobile website(toolbar and headline)
- Use flexbox on the 2 sections

2022-03-15 18:11 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @telanet, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 👏 

## Highlights
- Descriptive Readme 👍 
- All linters are passing 👍 
- Descriptive PR title and summary 👍 

- [ ] Kindly _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-15 18:11 UTC, sja-thedude commented on style.css
> +  background-image: url(/img/Illustration.png);
- [ ] Make sure this background image works. Right now it's not displaying the background image in your design. Kindly fix this.
- Your design -
<img width="376" alt="Screenshot 2022-03-15 at 8 52 35 PM" src="https://user-images.githubusercontent.com/70269507/158442678-bfe80551-2ca2-4872-b57f-65f560c71b13.png">

- Figma design -
<img width="349" alt="Screenshot 2022-03-15 at 8 52 11 PM" src="https://user-images.githubusercontent.com/70269507/158442761-29bab2a2-fdcd-4627-af69-4b257906c1f0.png">

2022-03-16 07:09 UTC, Kingstalux commented on style.css
> +  color: #ff6b00;
resolved 👍

2022-03-16 07:09 UTC, Kingstalux commented on style.css
> +}
resolved 👍

2022-03-16 07:10 UTC, Kingstalux commented on style.css
> +  background-image: url(/img/Illustration.png);
not resolved

2022-03-16 07:14 UTC, Kingstalux approved these changes
Hi @ksigei,
# Status: Approved ✔️ ✔️ ✔️ 
 
![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/85113567/158536210-7553771d-9e55-43c1-a88d-f501961efe1e.gif)

Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 07:32 UTC, merged