Popup modal
telanet/My-Portfolio pull request #11
Opened 2022-04-07 14:02 UTC by telanet

In this milestone, we implemented the following:

- Popup with details about the project when the user clicks the button.
- The popup disappears when the close (X) button, is clicked.

2022-04-07 14:31 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @telanet,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-07 14:31 UTC, Omar-Muhamad commented on stylesheets/popup.css
> +  font-weight: 400;
- [ ] Kindly fix the styling of the popup card in the mobile view by adding the correct width value and fixing the widths, margins, and paddings for all popup card elements because now you have side-scrolling in your page, and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/162221206-c844734b-3098-4166-9bf1-ca92d46ae513.png)  | ![chrome-capture-2022-3-7 (3)](https://user-images.githubusercontent.com/68796232/162221025-e636f474-729b-4ab7-915e-c01f9fcbf7d6.gif) |

2022-04-07 14:31 UTC, Omar-Muhamad commented on stylesheets/popup.css
> +  }
- [ ] And for the desktop view Please add a margin-top to the work card.
- [ ] I can see the buttons are overflowing from the design so please fix that.
- [ ] Kindly there is a white background to the close button and it does not exist in the Figma design so Please fix that and try to stick as much as possible to the given Figma design.

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/162222897-1e72bd95-e249-4b4a-a646-062993a8a36f.png)  | ![image](https://user-images.githubusercontent.com/68796232/162222840-487c090f-950a-4175-9bd4-f5d61d5e04c1.png)  |

2022-04-08 10:53 UTC, BenMukebo requested changes
Hi @telanet,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

[OPTIONAL] Please it will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser.


- [OPTIONAL ] Linters are tools that perform static analysis on software in order to recognize and report adherence/non-adherence to some set of coding best practices. Please Instead of disabling the client, it will be nice to fix all linter errors manually.

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-08 10:53 UTC, BenMukebo commented on stylesheets/popup.css
> +  display: flex;
[OPTIONAL ] Kindly make the under background blurry when the popup windows is open, this will make the popup matches the Figma more closely 👍🏿

- you can remove the `background: #979493;` use instead the blur effect [blur() - CSS](https://developer.mozilla.org/fr/docs/Web/CSS/filter-function/blur)



Your Implementation | Figma Design
:---:|:---:
![pppppppppppppppppppp](https://user-images.githubusercontent.com/79058364/162421238-b9ff3919-9210-43cb-891a-3784dc3c71b5.png) | ![pppgggggggggggggggggg](https://user-images.githubusercontent.com/79058364/162421446-c064633e-b91a-4b1e-a56f-602dc5fec16b.png)

2022-04-08 10:53 UTC, BenMukebo commented on stylesheets/popup.css
> +.popup {
- [ ] As required by the previous reviewer, Add margin or padding-top to your popup window so that to prevent it the be attach to the  navigation bar

![pppppppppppppppppppppppppppppppppppp](https://user-images.githubusercontent.com/79058364/162421889-6760dec2-e68c-4c21-989f-6e96d63cf80f.png)

2022-04-08 11:54 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

## Please, before merging, fix my OPTIONAL suggestion:

- [ ] Kindly fix the menu links and try to make it close to the original Figma design:

> Your version
<img width="388" alt="Screen Shot 2022-04-08 at 15 52 55" src="https://user-images.githubusercontent.com/49064106/162430653-f4ec8fe8-9db2-47ec-8bda-ed3d34451777.png">

> Figma design
<img width="304" alt="Screen Shot 2022-04-08 at 15 52 45" src="https://user-images.githubusercontent.com/49064106/162430673-161b944f-56d1-47f6-a841-9aca18c81d4d.png">

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-08 13:11 UTC, merged