Portfolio Mobile menu
telanet/My-Portfolio pull request #9
Opened 2022-04-04 15:53 UTC by telanet

### In this milestone we implemented the following:
When the user clicks (or taps) the hamburger button, the mobile menu appears.
When the user clicks (or taps) the close (X) button, the mobile menu disappears.
When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2022-04-04 16:45 UTC, ShoiraTa requested changes
Hi @telanet ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-04 16:45 UTC, ShoiraTa commented on index.html
> +        <li class="list-item-icon"><a href="#" class="link link-icon fab fa-medium-m"></a></li>
- [ ] OPTIONAL: Please decrease the size of icons, after introduced changes, they become huge: 
<img width="255" alt="Screenshot 2022-04-04 at 20 39 55" src="https://user-images.githubusercontent.com/77038610/161591250-010708ca-98ec-4475-a534-65b4e4493b90.png">

2022-04-04 16:45 UTC, ShoiraTa commented on script.js
> +};
- [ ] After user clicks some menu item, `overflow = hidden;` property stays there and does not allow users to scroll up and down. Kindly remove overflow = 'hidden'; property when mobile menu is not open ⭐ 

https://user-images.githubusercontent.com/77038610/161591751-80e31341-de25-49a6-bfdc-f8f35bdeca29.mp4

2022-04-05 06:13 UTC, Meltrust approved these changes
Hi @telanet,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for correcting the icons, and removing the `overflow:hidden` property, thus correcting the flow of your menu, as requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-05 12:42 UTC, merged